test-pattern: # Configure exclusions for test sources
  active: true
  patterns: # Test file regexes
    - '.*/test/.*'
    - '.*/androidTest/.*'
    - '.*Test.kt'
    - '.*Spec.kt'
    - '.*Spek.kt'
  exclude-rule-sets:
    - 'comments'
  exclude-rules:
    - 'NamingRules'
    - 'WildcardImport'
    - 'MagicNumber'
    - 'MaxLineLength'
    - 'LateinitUsage'
    - 'StringLiteralDuplication'
    - 'SpreadOperator'
    - 'TooManyFunctions'
    - 'ForEachOnRange'
    - 'FunctionMaxLength'
    - 'TooGenericExceptionCaught'
    - 'InstanceOfCheckForException'

processors:
  active: true

complexity:
  ComplexMethod:
    active: true
    threshold: 10
    ignoreSingleWhenExpression: false
    ignoreSimpleWhenEntries: false
  NestedBlockDepth:
    active: true
    threshold: 3
  LongMethod:
    active: true
    threshold: 30
  LongParameterList:
    active: true
    threshold: 6
    ignoreDefaultParameters: false
  ComplexCondition:
    active: true
    threshold: 3

potential-bugs:
  active: true
  MissingWhenCase: